FROM ubuntu:18.04
RUN apt-get update && \
  apt-get install -y libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev python-zmq zlib1g-dev wget curl bsdmainutils automake cmake clang libsodium-dev libcurl4-gnutls-dev libssl-dev git unzip python jq htop

RUN mkdir /opt/komodo
WORKDIR /opt/komodo

RUN git clone https://github.com/komodoplatform/komodo.git && \
  cd komodo && \
  git checkout master && \
  ./zcutil/build.sh -j4 && \
  ./zcutil/fetch-params.sh

# from https://rtfm.co.ua/en/docker-configure-tzdata-and-timezone-during-build/
ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
  echo $TZ > /etc/timezone

RUN apt-get install -y php php-gmp

# EXPOSE p2p port for the node to communicate on p2p network
ARG P2P_PORT
EXPOSE $P2P_PORT
# EXPOSE rpc port for the node to allow outside container access
ARG RPC_PORT
EXPOSE $RPC_PORT

ARG BLOCKCHAIN_DATA_PATH
RUN mkdir $BLOCKCHAIN_DATA_PATH -p
